#!/usr/bin/env bash

workflow_plist_path="workflow/info.plist"
if [[ -f $workflow_plist_path ]]; then
    dont_export=$(/usr/libexec/PlistBuddy -c 'print variablesdontexport' $workflow_plist_path | grep '    ' | sed -E 's/ {4}//')

    echo "${dont_export}" | while IFS= read -r v; do
        if [[ $(/usr/libexec/PlistBuddy -c "print variables:$v" $workflow_plist_path) ]]; then
            echo "You can't commit $v in the workflow/info.plist (Workflow config)."
            exit 1
        fi
    done
fi
